// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	seckill "gomall/apps/seckill/cmd/api/internal/handler/seckill"
	"gomall/apps/seckill/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/seckill",
				Handler: seckill.CreateSeckillHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/order/v1"),
	)
}
