Name: product.rpc
ListenOn: 127.0.0.1:2003
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc

DB:
  DataSource: root:123456@tcp(127.0.0.1:3306)/gomall_product?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Prometheus:
  Host: 0.0.0.0
  Port: 4006
  Path: /metrics

Redis:
   Host: 127.0.0.1:6379
   Type: node
   Pass:
   Key:

Cache:
  - Host: 127.0.0.1:6379
    Pass:

BizRedis:
   Host: 127.0.0.1:6379
   Pass:
   Type: node

Telemetry:
   Endpoint: http://127.0.0.1:14268/api/traces