// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	product "gomall/apps/product/cmd/api/internal/handler/product"
	"gomall/apps/product/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product/productList",
				Handler: product.ProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/productDetail",
				Handler: product.ProductDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/product/v1"),
	)
}
