// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gomall/apps/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/createOrder",
				Handler: createOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/OrderList",
				Handler: OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/OrderDetail",
				Handler: OrderDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/order/v1"),
	)
}
