// Code generated by goctl. DO NOT EDIT.
package types

type Orders struct {
	Id          string  `json:"id"`          //订单id
	Sn          string  `json:"sn"`          //订单编号
	Userid      uint64  `json:"userid"`      //用户id
	Payment     float64 `json:"payment"`     //实际付款金额,单位是元,保留两位小数
	Paymenttype int8    `json:"paymenttype"` //支付类型,1-在线支付
	Postage     int     `json:"postage"`     //运费,单位是元
	Status      int16   `json:"status"`      //订单状态:0-已取消-10-未付款，20-已付款，30-待发货 40-待收货，50-交易成功，60-交易关闭
	CreateTime  int64   `json:"create_time"` //创建时间
	UpdateTime  int64   `json:"update_time"` //更新时间
}

type AddOrderReq struct {
	ProductId int64 `json:"productId"`
	Quantity  int64 `json:"quantity"`
	UserId    int64 `json:"userId"`
	Postage   int64 `json:"postage"`
}

type AddOrderResp struct {
	Sn string `jaon:"sn"`
}

type OrderListView struct {
	ProductId     int64   `json:"productId"`
	ProductName   string  `json:"productName"`
	ProductDetail string  `json:"productDetail"`
	OrderId       string  `json:"orderId"`
	State         int64   `json:"state"`
	Quantity      int64   `json:"quantity"`
	Payment       float64 `json:"payment"`
	TotalPrice    float64 `json:"totalPrice"`
	CreatTime     int64   `json:"creatTime"`
	TradeCode     string  `json:"tradeCode"`
}

type OrderListReq struct {
	LastId     int64 `json:"lastId"`
	PageSize   int64 `json:"pageSize"`
	TradeState int64 `json:"tradeState"`
}

type OrderListResp struct {
	List []OrderListView `json:"list"`
}

type OrderDetailReq struct {
	OrderId string `json:"orderId"`
}

type OrderDetailResp struct {
	OrderId     string `json:"orderId"`
	UserId      int64  `json:"userId"`
	ProductId   int64  `json:"productId"`
	ProductName string `json:"productName"`
	TotalPrice  int64  `json:"totalPrice"`
	CreatTime   int64  `json:"creatTime"`
	State       string `json:"state"`
	TradeCode   string `json:"tradeCode"`
	PayTime     int64  `json:"payTime"`
	PayType     string `json:"payType"`
}
