// Code generated by goctl. DO NOT EDIT.
package types

type Product struct {
	Id          int64   `json:"id"`
	Name        string  `json:"Name"`
	Info        string  `json:"info"`
	Description string  `json:"description"` // 商品描述
	Price       float64 `json:"price"`       // 商品价格
	Stock       int64   `json:"stock"`       // 库存
	Status      int64   `json:"status"`      // 状态：1-正常，2-下架
	CreateTime  int64   `json:"create_time"` // 创建时间
	UpdateTime  int64   `json:"update_time"` // 更新时间
}

type ProductListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type ProductListResp struct {
	List []Product `json:"list"`
}

type ProductDetailReq struct {
	Id int64 `json:"id"`
}

type ProductDetailResp struct {
	Product Product `json:"product"`
}
