// Code generated by goctl. DO NOT EDIT.
package types

type PaymentReq struct {
	OrderSn     string `json:"orderSn"`
	SerivceType string `json:"serivceType"`
}

type PaymentResp struct {
	PaySn string `json:"pay"`
}
