Name: product
Host: 0.0.0.0
Port: 1003
Mode: dev

Prometheus:
  Host: 0.0.0.0
  Port: 4005
  Path: /metrics

DB:
  DataSource: root:123456@tcp(127.0.0.1:3306)/gomall_product?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Cache:
  - Host: 127.0.0.1:6379
    Pass:

ProductRpcConf:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: product.rpc
  NonBlock: true



Telemetry:
  Endpoint: http://127.0.0.1:14268/api/traces