// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	payment "gomall/apps/payment/cmd/api/internal/handler/payment"
	"gomall/apps/payment/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/Payment/Payment",
				Handler: payment.PaymentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/payment/v1"),
	)
}
